apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - name: users-api
          image: acrformymicroservices.azurecr.io/users-api:latest
          ports:
            - containerPort: 8083
          env:
            - name: JWT_SECRET
              value: "PRFT"
            - name: SERVER_PORT
              value: "8083"
---
apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: microservices
spec:
  selector:
    app: users-api
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
