name: CI/CD Pipeline - Development

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    - name: Set up Google Cloud Docker authentication
      run: |
        gcloud auth configure-docker
    - name: Set up DockerHub Login
      uses: docker/login-action@v2
      with:
        username: lacragh
        password: victor9043

    - name: Build auth-api
      run: |
        docker build -t lacragh/auth-api ./auth-api
    - name: Build users-api
      run: |
        docker build -t lacragh/users-api ./users-api
    - name: Build todos-api
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/todos-api ./todos-api
    - name: Build frontend
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend ./frontend
    

    - name: Push Docker images
      run: |
        docker push lacragh/auth-api
        docker push lacragh/users-api
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/todos-api
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend

